[theme]
# Primary accent color for interactive elements.
primaryColor = "#FBFCFC"

# Background color for the main content area.
backgroundColor = "#17202A"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#283747"

# Color used for almost all text.
textColor = "#85C1E9"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
